[theme]
base="dark"
#primaryColor="#460C68"
#backgroundColor="#460C68"
secondaryBackgroundColor="#303037"
textColor="#e49633"
font="Helvetica"

#Definir la police et la color
#https://fonts.google.com/
#https://colorhunt.co/
    """Arial
    Helvetica
    Verdana
    Times New Roman
    Georgia
    Courier New
    Lucida Console
    Tahoma
    Calibri
    Palatino
    Garamond
    Futura
    Century Gothic
    Trebuchet MS
    Book Antiqua
    Franklin Gothic Medium
    Roboto
    sans serif
    Open Sans
    Lato
    Montserrat"""